apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tekton-python-test-pipeline
spec:
  params:
    - name: git-url
    - name: git-revision
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: pytest
      taskRef:
        name: pytest
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: PYTHON
          value: "3.7"
        - name: ARGS
          value: "-rfs"
        - name: SOURCE_PATH
          value: "sync/."